name: Dependabot Jira

on:
  pull_request:
    types:
      - opened
    branches:
      - master

env:
  JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}
  JIRA_USER_EMAIL: ${{ vars.JIRA_USER_EMAIL }}
  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  JIRA_PROJECT: ${{ vars.JIRA_PROJECT_KEY }}
  JIRA_ISSUE_TYPE: ${{ vars.JIRA_ISSUE_TYPE }}

jobs:
  create_jira:
    name: Dependabot Jira
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login  == 'dependabot[bot]' # lookup by ID seems not to work
    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v3.0.1
      env:
        JIRA_BASE_URL: ${{ env.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v3.0.1
      with:
        project: ${{ env.JIRA_PROJECT }}
        issuetype: ${{ env.JIRA_ISSUE_TYPE }}
        summary: |
          [${{github.event.repository.name }}] ${{github.event.pull_request.title }}
        description: |
          ${{github.event.pull_request.html_url }}
